mash-up-kr/MOIT-backend

.editorconfig, gradle.properties, http/sample.http, moit-api/src/main/kotlin/com/mashup/moit/sample/controller/SampleController.kt, moit-common/src/main/kotlin/com/mashup/moit/common/exception/MoitException.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/common/BaseEntity.kt
코드 컨벤션을 통일하기 위해 `editorconfig` 파일을 추가하고 적용했습니다.
Intellij 적용법은 구글에 치면 나오는데, [이 글](https://blog.benelog.net/ktlint.html#intellij_%EC%84%A4%EC%A0%95) 참조하시면 좋을 것 같아요.
(왠만하면 자동으로 잡히던 것 같음)
코드 수정 후 reformat 습관들이고 이상하면 그때마다 수정하는 식으로 합시다!
=> style: Editorconfig 적용

.github/workflows/CD.yml, deploy/Dockerrun.aws.json
elasticbeanstalk github actions CD 입니다. 
아마 실행이 안될 수도 있어서 master branch 에 머지되어봐야 알 것 같습니다
=> config : add ebs cd

.github/workflows/CD.yml
=> fix : tags in cd

moit-api/src/main/resources/application.yml, moit-domain/src/main/resources/application-domain-dev.yml, moit-domain/src/main/resources/application-domain-release.yml, moit-domain/src/main/resources/application-domain.yml
=> chore: separate phase yml file

.github/workflows/CD.yml, deploy/Dockerrun.aws.json, moit-domain/src/main/resources/application-domain.yml
기존 docker file 기반으로 docker image build push 방식을 
#7 에서 적용한 jib 를 통해 CD 에서 사용하게 변경하였습니다.
=> fix : docker image process by jib in cd & db url 

.github/workflows/CD.yml, moit-api/build.gradle.kts, moit-domain/src/main/resources/application-domain.yml
close #31 
- docker container 에 환경 변수 injection 방법 변경했습니다
- secret value 잘못 들어간 것 같아서 해당 부분도 변경했습니다
=> fix : jib environment variables inject 

build.gradle.kts, gradle.properties
kotest spring extension version 잘못 작성한 것 수정.
=> hotfix: kotest spring extension version to 1.1.3

.github/workflows/pr.yml
Pull request에서도 빌드 및 테스트가 제대로 되는지 확인하기 위해서 Workflow를 추가하였습니다.
=> chore: Pull request workflow 추가

moit-api/src/main/kotlin/com/mashup/moit/study/controller/StudyController.kt, moit-api/src/main/kotlin/com/mashup/moit/study/controller/dto/StudyDto.kt
#38 
---
ref: [3) 스터디 출석 요청 (출석한 사람 있는지 확인 여부) API](https://www.notion.so/3-API-d0eda289f2ef4064abce96c77f80863d?pvs=4)
=> feat: Study 첫 출석자 존재 유무 확인 API (mock)

http/http-client.env.json, moit-api/src/main/kotlin/com/mashup/moit/study/controller/StudyController.kt, moit-api/src/main/kotlin/com/mashup/moit/study/controller/dto/StudyDto.kt
출석 코드를 등록 및 검증하는 Mock API 추가했습니다
두 API는 Response로 특별한 데이터를 응답하고 있지 않아 data에 null를 넣어주었습니다
#46 브랜치 머지 이후 rebase & merge 진행할 예정입니다. 머지 하지 말아주세용
=> Create MockServer for register/verify attendance code

moit-domain/src/main/kotlin/com/mashup/moit/domain/attendance/AttendanceEntity.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/fine/FineEntity.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/moit/MoitEntity.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/study/StudyEntity.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/study/StudyService.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/user/UserEntity.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/usermoit/UserMoitEntity.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/usermoit/UserMoitRepository.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/usermoit/UserMoitService.kt
=> feat: remove unnecessary ManyToOne

moit-api/src/main/kotlin/com/mashup/moit/moit/controller/MoitController.kt, moit-api/src/main/kotlin/com/mashup/moit/moit/controller/dto/MoitDto.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/moit/MoitService.kt
조회하려는 모잇의 모든 출결 정보를 내려주는 API 입니다.
#44 브랜치 머지 이후 머지할 예정입니다.
=> Add Moit Study Attendance List API to MoitController

moit-api/src/main/kotlin/com/mashup/moit/study/controller/StudyController.kt, moit-api/src/main/kotlin/com/mashup/moit/study/controller/dto/StudyDto.kt, moit-api/src/main/kotlin/com/mashup/moit/study/facade/StudyFacade.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/study/StudyService.kt
close #55 
키워드 출석 조회 API 입니다. 
- 서비스 내 메서드는 출석 키워드 인증에서도 사용될 것 고려하여 작성하였습니당
=>  study attendance code 조회 API

moit-api/src/main/kotlin/com/mashup/moit/moit/controller/MoitController.kt, moit-api/src/main/kotlin/com/mashup/moit/moit/controller/dto/MoitDto.kt, moit-api/src/main/kotlin/com/mashup/moit/moit/facade/MoitFacade.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/moit/MoitService.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/usermoit/UserMoitRepository.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/usermoit/UserMoitService.kt
close #52 
moit detail 조회 API 입니다!
=> Moit deatils API

http/study.http, moit-api/src/main/kotlin/com/mashup/moit/study/controller/StudyController.kt, moit-api/src/main/kotlin/com/mashup/moit/study/controller/dto/StudyDto.kt, moit-api/src/main/kotlin/com/mashup/moit/study/facade/StudyFacade.kt, moit-common/src/main/kotlin/com/mashup/moit/common/exception/MoitExceptionType.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/attendance/Attendance.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/attendance/AttendanceEntity.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/attendance/AttendanceRepository.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/attendance/AttendanceService.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/user/User.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/user/UserEntity.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/user/UserService.kt
- 스터디 참여자 출석 상태 조회 API 입니다.
- API 번호 2 입니다. ([Notion](https://www.notion.so/2-API-19b5b1c9672f4823b047f262f498f1a4?pvs=4))
=> feat: get study attendance status api

moit-api/src/main/kotlin/com/mashup/moit/fine/controller/FineController.kt, moit-api/src/main/kotlin/com/mashup/moit/fine/facade/FineFacade.kt, moit-api/src/main/kotlin/com/mashup/moit/moit/facade/MoitFacade.kt, moit-common/src/main/kotlin/com/mashup/moit/common/exception/MoitExceptionType.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/fine/FineEntity.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/fine/FineService.kt
=> feat: 벌금 인증(허용여부) API

gradle.properties, moit-api/build.gradle.kts, moit-api/src/main/kotlin/com/mashup/moit/config/SecurityConfig.kt, moit-api/src/main/kotlin/com/mashup/moit/fine/controller/FineController.kt, moit-api/src/main/kotlin/com/mashup/moit/fine/controller/dto/FineDto.kt, moit-api/src/main/kotlin/com/mashup/moit/fine/facade/FineFacade.kt, moit-api/src/main/kotlin/com/mashup/moit/infra/aws/AwsConfig.kt, moit-api/src/main/kotlin/com/mashup/moit/infra/aws/s3/S3Config.kt, moit-api/src/main/kotlin/com/mashup/moit/infra/aws/s3/S3Service.kt, moit-api/src/main/kotlin/com/mashup/moit/moit/facade/MoitFacade.kt, moit-api/src/main/kotlin/com/mashup/moit/security/authentication/MoitUser.kt, moit-api/src/main/resources/application.yml, moit-common/src/main/kotlin/com/mashup/moit/common/exception/MoitExceptionType.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/fine/Fine.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/fine/FineEntity.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/fine/FineService.kt
벌금 인증 Endpoint
- 이미지 업로드를 위한 AWS, S3 configuration classes 추가
- `approveImageUrl` 이름이 어색해서 `paymentImageUrl`로 수정
- 이미지 업로드 후 주소를 Fine paymentImageUrl에 추가하는 로직 추가
=> feat: 벌금 인증

moit-api/src/main/kotlin/com/mashup/moit/config/OpenApiConfig.kt, moit-api/src/main/kotlin/com/mashup/moit/config/SecurityConfig.kt, moit-api/src/main/kotlin/com/mashup/moit/facade/UserFacade.kt, moit-api/src/main/kotlin/com/mashup/moit/security/resolver/UserInfoArgumentResolver.kt, moit-api/src/main/kotlin/com/mashup/moit/util/Constant.kt, moit-api/src/main/resources/application.yml, moit-api/src/test/kotlin/com/mashup/moit/security/jwt/JwtTokenSupporterTest.kt
- Security 활성화
- 로그인 로직/Swagger 등을 제외한 모든 엔드포인트에 JWT 인증 필요
- Swagger JWT 설정 추가
- 회원가입 중복 방지 로직 추가
=> feat: Security - 5

moit-api/src/main/kotlin/com/mashup/moit/moit/controller/MoitController.kt, moit-api/src/main/kotlin/com/mashup/moit/study/controller/StudyController.kt
=> feat: apply GetAuth annotation

moit-api/src/main/kotlin/com/mashup/moit/moit/controller/dto/MoitDto.kt, moit-api/src/main/kotlin/com/mashup/moit/moit/facade/MoitFacade.kt
moit 가입 완료 이후 엔드페이지 정보가 바뀌어서, response 변경하였습니다
=> update: moit join response

moit-api/src/main/kotlin/com/mashup/moit/config/SecurityConfig.kt, moit-api/src/main/resources/application.yml
auth0 계정을 개인 주소를 이용하고 있었는데요.
전자군단 주소로 변경했습니다.
=> feat: auth0 주소 업데이트

moit-api/src/main/kotlin/com/mashup/moit/controller/moit/MoitController.kt, moit-api/src/main/kotlin/com/mashup/moit/facade/FineFacade.kt, moit-api/src/main/kotlin/com/mashup/moit/facade/MoitFacade.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/fine/FineService.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/moit/MoitEntity.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/moit/MoitService.kt
moit profile image 추가할 수 있도록 upload endpoint 추가했습니다.
- 부가적으로 fine image upload하고 네이밍 `add~`로 합쳐주려고 rename도 진행했습니다.
=> feat: Moit image 업로드

moit-api/src/main/kotlin/com/mashup/moit/controller/user/UserController.kt, moit-api/src/main/kotlin/com/mashup/moit/facade/UserFacade.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/user/UserEntity.kt, moit-domain/src/main/kotlin/com/mashup/moit/domain/user/UserService.kt
회원탈퇴 API를 추가했습니다.
- is_deleted 필드를 사용할 수 있도록 Where/SQLDelete 사용해 적절한 쿼리 사용할 수 있도록 설정했습니다.
=> feat: 회원탈퇴 API

moit-api/src/main/kotlin/com/mashup/moit/controller/fine/dto/FineDto.kt
클라이언트 측 요구사항으로 벌금 DTO 관련 수정되었습니다.
- approve status 반환. isApprove 대신 더 상세한 정보를 확인할 수 있도록 status 자체 반환.
- payment image url 반환
=> feat: 벌금 DTO 수정
